-- Reverse G03-03 only; leave G03-01/G03-02 canonical identities untouched.
drop trigger if exists import_product_guard on products;
drop trigger if exists import_version_guard on product_versions;
drop trigger if exists import_artifact_guard on artifacts;
drop trigger if exists import_asset_guard on assets;
drop trigger if exists import_pattern_guard on patterns;
drop function if exists skelet_import_ref_delete_guard();
drop trigger if exists import_immutable_guard on import_records;
drop function if exists skelet_import_immutable();
drop trigger if exists import_target_guard on import_records;
drop table if exists import_records;
drop function if exists skelet_import_target_guard();
drop trigger if exists analysis_run_insert on analysis_runs;
drop trigger if exists capture_run_insert on capture_runs;
drop trigger if exists analysis_run_transition on analysis_runs;
drop trigger if exists capture_run_transition on capture_runs;
drop table if exists analysis_runs;
drop table if exists capture_runs;
drop index if exists capture_source_id_id_uq;
drop function if exists skelet_run_transition_guard();
drop function if exists skelet_run_insert_guard();
drop table if exists collection_items;
drop table if exists collections;
drop trigger if exists flow_artifact_parent_guard on artifacts;
drop trigger if exists flow_version_parent_guard on product_versions;
drop trigger if exists flow_product_parent_guard on products;
drop function if exists skelet_flow_parent_guard();
drop trigger if exists flow_step_integrity on flow_steps;
drop table if exists flow_steps;
drop trigger if exists flow_source_guard on flows;
drop table if exists flows;
drop function if exists skelet_flow_source_guard();
drop function if exists skelet_flow_step_integrity();
